// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Load .env file explicitly
config({ path: ".env" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL || "postgresql://erwan@localhost:5432/geek_gaming_db",
    directUrl: "postgresql://erwan@localhost:5432/geek_gaming_db?sslmode=prefer",
  },
});
